ALTER TABLE UNIGRASAS.FACTURA AUTO_INCREMENT = 191;


-- ANOS VENTAS
SELECT DATE_FORMAT(F_PAGO, '%Y') ANOS FROM FACTURA
GROUP BY DATE_FORMAT(F_PAGO, '%Y');

-- MESES X ANO DE VENTA
SELECT CONVERT((DATE_FORMAT(F_PAGO, '%m')), SIGNED INTEGER) MES FROM FACTURA
WHERE DATE_FORMAT(F_PAGO, '%Y') = 2021
GROUP BY DATE_FORMAT(F_PAGO, '%m');

-- CLIENTES CON VENTAS TERMINADAS
SELECT C.IDCLIENTE, C.NOMBRE FROM FACTURA F, CLIENTE C
WHERE IDESTADO = 2
AND F.IDCLIENTE = C.IDCLIENTE
AND DATE_FORMAT(F.F_PAGO, '%Y') = 2021
AND DATE_FORMAT(F.F_PAGO, '%m') = 3
GROUP BY C.IDCLIENTE, C.NOMBRE;

-- USUARIOS ASOCIADOS A VENTAS X CLIENTE
SELECT U.IDUSUARIO, U.NOMBRE FROM FACTURA F, USUARIO U
WHERE IDESTADO = 2
AND F.IDUSUARIO = U.IDUSUARIO
AND F.IDCLIENTE = 5
AND DATE_FORMAT(F.F_PAGO, '%Y') = 2021
AND DATE_FORMAT(F.F_PAGO, '%m') = 3
GROUP BY U.IDUSUARIO, U.NOMBRE;

-- PRODUCTOS ASOCIADOS A VENTAS X CLIENTE X USUARIO
SELECT FI.IDITEM, I.NOMBRE FROM FACTURA F, FACTURA_HAS_ITEM FI, ITEM I
WHERE F.IDFACTURA = FI.IDFACTURA
AND FI.IDITEM = I.IDITEM
AND F.IDCLIENTE = 5
AND F.IDUSUARIO = 3
AND DATE_FORMAT(F.F_PAGO, '%Y') = 2021
AND DATE_FORMAT(F.F_PAGO, '%m') = 3
GROUP BY FI.IDITEM, I.NOMBRE;

-- VENTAS TOTALES X PRODUCTO
SELECT FI.IDITEM, I.NOMBRE, FI.CANTIDAD, FI.PRECIO, SUM(FI.CANTIDAD * FI.PRECIO) TOTAL FROM FACTURA F, FACTURA_HAS_ITEM FI, ITEM I
WHERE F.IDFACTURA = FI.IDFACTURA
AND FI.IDITEM = I.IDITEM
AND F.IDCLIENTE = 5
AND F.IDUSUARIO = 3
AND FI.IDITEM = 4
AND DATE_FORMAT(F.F_PAGO, '%Y') = 2021
AND DATE_FORMAT(F.F_PAGO, '%m') = 3
GROUP BY FI.IDITEM, I.NOMBRE;

-- VENTAS TOTALES X ANO
SELECT DATE_FORMAT(F.F_PAGO, '%Y') ANO, SUM(F.TOTAL) VENTAS FROM FACTURA F
WHERE
DATE_FORMAT(F.F_PAGO, '%Y') = 2021
GROUP BY DATE_FORMAT(F.F_PAGO, '%Y');

-- VENTAS TOTALES X ANO X MES
SELECT DATE_FORMAT(F.F_PAGO, '%Y') ANO, DATE_FORMAT(F.F_PAGO, '%m') MES, SUM(F.TOTAL) VENTAS FROM FACTURA F
WHERE
DATE_FORMAT(F.F_PAGO, '%Y') = 2021
AND DATE_FORMAT(F.F_PAGO, '%m') = 2
GROUP BY DATE_FORMAT(F.F_PAGO, '%Y'), DATE_FORMAT(F.F_PAGO, '%m');

-- VENTAS TOTALES X ANO X MES X CLIENTE X USUARIO X PRODUCTO
SELECT DATE_FORMAT(F.F_PAGO, '%Y') ANO, DATE_FORMAT(F.F_PAGO, '%m') MES, SUM(FI.CANTIDAD * FI.PRECIO) TOTAL FROM FACTURA F, FACTURA_HAS_ITEM FI, ITEM I
WHERE F.IDFACTURA = FI.IDFACTURA
AND FI.IDITEM = I.IDITEM
AND (F.IDCLIENTE = 5)
AND (F.IDUSUARIO = 3)
AND (FI.IDITEM IN (4, 11))
AND (DATE_FORMAT(F.F_PAGO, '%Y') = 2021)
AND (DATE_FORMAT(F.F_PAGO, '%m') = 3)
GROUP BY DATE_FORMAT(F.F_PAGO, '%Y'), DATE_FORMAT(F.F_PAGO, '%m');