DROP TABLE FACTURA_HAS_ITEM;
DROP TABLE FACTURA;
DROP TABLE USUARIO;
DROP TABLE EMPRESA;
DROP TABLE CLIENTE;
DROP TABLE ESTADO;
DROP TABLE GENERO;
DROP TABLE ITEM;
DROP TABLE MEDIO_PAGO;
DROP TABLE METODO_PAGO;
DROP TABLE ROL;
DROP TABLE TIPO_PERSONA;

-- -----------------------------------------------------
-- TABLE TIPO_PERSONA
-- -----------------------------------------------------
CREATE TABLE TIPO_PERSONA (
  IDTIPO_PERSONA SERIAL NOT NULL,
  NOMBRE TEXT NULL,
  PRIMARY KEY (IDTIPO_PERSONA));

-- -----------------------------------------------------
-- TABLE CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE (
  IDCLIENTE SERIAL NOT NULL,
  IDTIPO_PERSONA INTEGER NOT NULL,
  NIT TEXT NULL DEFAULT NULL,
  NOMBRE TEXT NULL DEFAULT NULL,
  DIRECCION TEXT,
  EMAIL TEXT NULL DEFAULT NULL,
  TELEFONO BIGINT NULL DEFAULT NULL,
  F_REGISTRO TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
  PRIMARY KEY (IDCLIENTE),
  CONSTRAINT FK_CLIENTE_TIPO_PERSONA1
    FOREIGN KEY (IDTIPO_PERSONA)
    REFERENCES TIPO_PERSONA (IDTIPO_PERSONA));
	
CREATE INDEX FK_CLIENTE_TIPO_PERSONA1_IDX ON CLIENTE (IDTIPO_PERSONA);


-- -----------------------------------------------------
-- TABLE EMPRESA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EMPRESA (
  IDEMPRESA SERIAL NOT NULL,
  IDTIPO_PERSONA INTEGER NOT NULL,
  NIT BIGINT NULL DEFAULT NULL,
  DIGITO_VERIFICACION INTEGER NULL DEFAULT NULL,
  RAZON_SOCIAL TEXT NULL DEFAULT NULL,
  DIRECCION TEXT NULL DEFAULT NULL,
  PAIS TEXT NULL DEFAULT NULL,
  CIUDAD TEXT NULL DEFAULT NULL,
  CIIU TEXT NULL DEFAULT NULL,
  MATRICULA BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (IDEMPRESA),
  CONSTRAINT FK_EMPRESA_TIPO_PERSONA1
    FOREIGN KEY (IDTIPO_PERSONA)
    REFERENCES TIPO_PERSONA (IDTIPO_PERSONA));
	
CREATE INDEX FK_EMPRESA_TIPO_PERSONA1_IDX ON EMPRESA (IDTIPO_PERSONA);


-- -----------------------------------------------------
-- TABLE MEDIO_PAGO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MEDIO_PAGO (
  IDMEDIO_PAGO SERIAL NOT NULL,
  NOMBRE TEXT NULL DEFAULT NULL,
  PRIMARY KEY (IDMEDIO_PAGO));


-- -----------------------------------------------------
-- TABLE METODO_PAGO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS METODO_PAGO (
  IDMETODO_PAGO SERIAL NOT NULL,
  NOMBRE TEXT NULL DEFAULT NULL,
  PRIMARY KEY (IDMETODO_PAGO));


-- -----------------------------------------------------
-- TABLE ROL
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ROL (
  IDROL SERIAL NOT NULL,
  NOMBRE TEXT NULL DEFAULT NULL,
  PRIMARY KEY (IDROL));


-- -----------------------------------------------------
-- TABLE GENERO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS GENERO (
  IDGENERO SERIAL NOT NULL,
  NOMBRE TEXT NULL,
  PRIMARY KEY (IDGENERO));


-- -----------------------------------------------------
-- TABLE USUARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS USUARIO (
  IDUSUARIO SERIAL NOT NULL,
  NOMBRE TEXT NULL DEFAULT NULL,
  APELLIDO TEXT NULL,
  IDGENERO INTEGER NOT NULL,
  NICKNAME TEXT NULL,
  DESCRIPCION TEXT NULL DEFAULT NULL,
  IDROL INTEGER NOT NULL,
  AVATAR TEXT NULL DEFAULT NULL,
  CONTRASENA TEXT NULL DEFAULT NULL,
  TOKEN TEXT NULL DEFAULT NULL,
  IDENTIFICACION BIGINT NULL,
  IDEMPRESA INTEGER NOT NULL,
  TELEFONO BIGINT NULL,
  EMAIL TEXT NULL,
  PRIMARY KEY (IDUSUARIO),
  CONSTRAINT FK_USUARIO_EMPRESA1
    FOREIGN KEY (IDEMPRESA)
    REFERENCES EMPRESA (IDEMPRESA),
  CONSTRAINT FK_USUARIO_ROL1
    FOREIGN KEY (IDROL)
    REFERENCES ROL (IDROL),
  CONSTRAINT FK_USUARIO_GENERO1
    FOREIGN KEY (IDGENERO)
    REFERENCES GENERO (IDGENERO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
	
CREATE INDEX FK_USUARIO_EMPRESA1_IDX ON USUARIO (IDEMPRESA);
CREATE INDEX FK_USUARIO_ROL1_IDX ON USUARIO (IDROL);
CREATE INDEX FK_USUARIO_GENERO1_IDX ON USUARIO (IDGENERO);


-- -----------------------------------------------------
-- TABLE ESTADO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ESTADO (
  IDESTADO SERIAL NOT NULL,
  NOMBRE TEXT NULL,
  PRIMARY KEY (IDESTADO));


-- -----------------------------------------------------
-- TABLE FACTURA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FACTURA (
  IDFACTURA SERIAL NOT NULL,
  IDCLIENTE INTEGER NOT NULL,
  IDMETODO_PAGO INTEGER NULL DEFAULT NULL,
  IDMEDIO_PAGO INTEGER NULL DEFAULT NULL,
  IDUSUARIO INTEGER NOT NULL,
  IDESTADO INTEGER NOT NULL,
  DIVISA TEXT NULL DEFAULT NULL,
  F_EMISION TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
  F_VENCIMIENTO TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
  F_PAGO TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
  TOTAL DECIMAL NULL DEFAULT NULL,
  DESCRIPCION TEXT NULL DEFAULT NULL,
  F_REGISTRO TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
  PRIMARY KEY (IDFACTURA),
  CONSTRAINT FK_FACTURA_CLIENTE1
    FOREIGN KEY (IDCLIENTE)
    REFERENCES CLIENTE (IDCLIENTE),
  CONSTRAINT FK_FACTURA_MEDIO_PAGO1
    FOREIGN KEY (IDMEDIO_PAGO)
    REFERENCES MEDIO_PAGO (IDMEDIO_PAGO),
  CONSTRAINT FK_FACTURA_METODO_PAGO1
    FOREIGN KEY (IDMETODO_PAGO)
    REFERENCES METODO_PAGO (IDMETODO_PAGO),
  CONSTRAINT FK_FACTURA_USUARIO1
    FOREIGN KEY (IDUSUARIO)
    REFERENCES USUARIO (IDUSUARIO),
  CONSTRAINT FK_FACTURA_ESTADO1
    FOREIGN KEY (IDESTADO)
    REFERENCES ESTADO (IDESTADO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
	
CREATE INDEX FK_FACTURA_CLIENTE1_IDX ON FACTURA (IDCLIENTE);
CREATE INDEX FK_FACTURA_METODO_PAGO1_IDX ON FACTURA (IDMETODO_PAGO);
CREATE INDEX FK_FACTURA_MEDIO_PAGO1_IDX ON FACTURA (IDMEDIO_PAGO);
CREATE INDEX FK_FACTURA_USUARIO1_IDX ON FACTURA (IDUSUARIO);
CREATE INDEX FK_FACTURA_ESTADO1_IDX ON FACTURA (IDESTADO);


-- -----------------------------------------------------
-- TABLE ITEM
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ITEM (
  IDITEM SERIAL NOT NULL,
  COD_ITEM INTEGER NOT NULL,
  NOMBRE TEXT NOT NULL,
  PRECIO DECIMAL NULL DEFAULT NULL,
  DESCRIPCION TEXT NULL DEFAULT NULL,
  F_REGISTRO TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
  PRIMARY KEY (IDITEM));


-- -----------------------------------------------------
-- TABLE FACTURA_HAS_ITEM
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FACTURA_HAS_ITEM (
  IDFACTURA INTEGER NULL,
  IDITEM INTEGER NULL,
  CANTIDAD BIGINT NULL DEFAULT NULL,
  PRECIO DECIMAL NULL DEFAULT NULL,
  CONSTRAINT FK_FACTURA_HAS_ITEM_FACTURA1
    FOREIGN KEY (IDFACTURA)
    REFERENCES FACTURA (IDFACTURA),
  CONSTRAINT FK_FACTURA_HAS_ITEM_ITEM1
    FOREIGN KEY (IDITEM)
    REFERENCES ITEM (IDITEM));
	
CREATE INDEX FK_FACTURA_HAS_ITEM_ITEM1_IDX ON FACTURA_HAS_ITEM (IDITEM ASC);
CREATE INDEX FK_FACTURA_HAS_ITEM_FACTURA1_IDX ON FACTURA_HAS_ITEM (IDFACTURA ASC);